### PR TITLE
Extend left-shift operator

### PR DESCRIPTION
**Pull request by slcasner**
As suggested, extend the left-shift operator to take negative shift values for right shift; optimize for 0 shift or shift greater than 15; and allow shifting symbols using multiply or divide for complex  relocation.

### CODE REVIEW

**Comment by Rhialto** [comment]
Thanks! I've cherry-picked the 2 new commits, because of the slight weirdness in the history line of the commits. That way I keep a nice linear history. So I'm closing the merge request and it may seem it isn't merged (technically true), but the commits have been applied.

**Comment by slcasner** [comment]
That's fine.  I'm not a git expert.  I thought that I needed to get my fork in sync with yours before applying the additional changes.  Perhaps I should have done that by rebase instead of merge.  Or should I just have made the additional change on my fork and then when you merged that's all that would have been needed to bring over even though you had made other commits in between?

**Comment by Rhialto** [comment]
They way github wants you to work is a bit tedious for casual contributions. They want you to fork the original repository, and then in your own fork create a new branch and work on that.

At least one disadvantage of that is that there is no easy way to keep your fork up to date wrt the original. You have to pull each branch you're interested in from the original and then push it to the fork (even if both are on github). Alternatively, throw it away and re-fork it every time (if you have no code of your own in it any more).

Gitlab is a bit better there: there is a standard UI to set that up so that it synchronizes automatically with a chosen upstream repository. 

But since I'm annoyed by projects where they will consider your contributions only if you're sticking *exactly* to the workflow they want (who can remember those details for all projects where you'd want to make a trivial contribution?) I try to be flexible about it.

**Comment by Rhialto** [comment]
Oh some of the history weirdness seems to be because I clicked "rebase and merge". Even though rebasing wasn't needed at that point, it still changed something to the commits, and then our versions diverged.

**Comment by slcasner** [comment]
There was some weirdness when I merged your fork into mine as well.  The removal of tabs in extree.h was shown as a conflict.  I had noticed that I left in tabs and so had edited them myself before noticing that you had fixed them as well, but I reset my local master branch back to my commit 5cb8ed30 and tried repeated the merge and it still showed as a conflict.

**Pull request closed without merging**
